### ISSUE TITLE
로그인 및 회원가입 구현(+API, -passport)

### ISSUE THREAD

**Issue by kanghyun98** [gdsc-ssu/sasil-server#7]
## Epic
https://github.com/gdsc-ssu/sasil-front/issues/11

## Description
소셜로그인 버튼만으로 로그인과 회원가입이 동시에 이뤄질 수 있도록 API를 구현한다.
그리고 특정 `request`는 로그인이 되어있는 경우에만 정상적으로 결과값이 반환되도록 검증 로직 구현한다.
추가적으로 로그인 시 프론트에서 tokenId를 받아와 인증하는 방식과 JWT를 사용하는 방식으로 리팩토링한다(`passport` 라이브러리 삭제)

## TODO
- [x] `login`/`getUser` api
- [x] `app.ts` 설정 추가
- [x] 로그인(처음이면 회원가입) 동작 확인
- [x] 라우터 검사 미들웨어 구현
- [x] 프로필, 닉네임 생성(init with null, 이름)
- [x] 로그인 방식 리팩토링 (TokenID, JWT)
