### ISSUE TITLE
서버 배포 환경 구축

### ISSUE THREAD

**Issue by aube-dev** [gdsc-ssu/sasil-server#9]
## Epic
gdsc-ssu/sasil-front#11

## Description
소셜 로그인 기능 구현, API 동작 테스트 등을 위해, 그리고 실제 프로덕션 서버 동작을 위해 백엔드 서버 호스팅을 준비하고 배포 환경을 구축한다. 호스팅은 AWS Elastic Beanstalk을 이용한다.

## TODO

- [x] AWS EC2 생성 및 연결
- [x] AWS RDS 생성 및 연결
- [x] 도메인 연결
- [x] https 설정 
- [x] SSL 인증서 설정
- [x] Swagger 설정
- [ ] 백엔드 CI/CD
- [x] 보안 관련 설정 (`hpp`, `helmet`)
- [x] api logger (`morgan`)
